server:
  port: 8081
spring:
  application:
    name: colin-demo
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        metadata:
          version: 1.0 # 稳定版本 1.0，灰度版本 2.0

